#ifndef QTWEBSERVER_GLOBAL_H
#define QTWEBSERVER_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QtCore/QObject>

#if defined(QTWEBSERVER_LIBRARY)
#  define QTWEBSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTWEBSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTWEBSERVER_GLOBAL_H
